# Generated by Django 5.0.6 on 2024-05-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(max_length=1, verbose_name='Оценка'),
        ),
    ]
