version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes: 
       - db-data:/var/lib/mysql
    networks:
       - backend
      

  django:
    build: .
    command: sh -c "sleep 30 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - django-data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
       - backend

networks:
  backend:
volumes:
  db-data:
  django-data: